# Generated by Django 4.1.7 on 2023-03-05 17:29

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.IntegerField(choices=[(1, 'ADMIN'), (2, 'VIP'), (3, 'CLIENT')], verbose_name='Тип пользователя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('birthday', models.CharField(max_length=30, verbose_name='дата рождения')),
                ('gender', models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, "DIDN'T CHOOSE")], verbose_name='Пол')),
                ('orientation', models.IntegerField(choices=[(1, 'STRAIGHT'), (2, 'GAY'), (3, 'LESBIAN')], verbose_name='Ориентация')),
                ('dump', models.IntegerField(choices=[(1, 'YES!'), (2, 'OF COURCE YES!'), (3, 'ABSOLUTELY CORRECT!'), (4, 'YES OF COURCE IT IS ABSOLUTELY CORRECT!')], verbose_name='Вы глупы?')),
                ('favorite_anime', models.CharField(default='Наруто', max_length=45, verbose_name='Любимое аниме')),
                ('marry', models.IntegerField(choices=[(1, 'MARRIED'), (2, 'SINGLE')], verbose_name='Семейное положение')),
                ('CITY', models.CharField(max_length=40, verbose_name='Город')),
                ('password_for_admins', models.CharField(max_length=50, verbose_name='Введите ещё раз пароль, что бы мы знали что вы его ещё помните')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
