# Generated by Django 4.1.7 on 2023-03-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0002_rename_city_customuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite_anime',
            field=models.CharField(max_length=45, verbose_name='Любимое аниме'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=25, verbose_name='номер телефона'),
        ),
    ]
